#!/bin/bash

#
# Create a list of timestamps with interesting action from the video snapshots taken by VLC media player.
#
# The video prefix format in VLC player need to be changed for this to work.
# Might be a bug in VLC but for norwegian keyboard '=' does not set normal playback speed. Changed that to 'q' as it was not mapped to anything.
#
# Jarl Even Englund May 2019



#
# In VLC Tools -> Settings >> Video Prefix
#
# https://wiki.videolan.org/Documentation:Play_HowTo/Format_String/
# 
# ___---___$T___---___$F___---___$t___---___
#
#  $T : time code of the video
#  $F : full name with path
#  $t : title


#
# Snapshots are created with VLC
#
#  Take snapshot:	Shift + s
#  Faster:		+
#  Slower:		-
#  Next frame:		e
#  Pause:		Space
#  Normal speed:	q		(Changed from '=', requires VLC restart)
#  Advance 10sec:	Alt + ->
#  Retreat 10sec:	Alt + <-
#
#  Edit metadata:	Ctrl + i	Use this to add a title to the video
#




# List png files
ls *.png -1a > rawlist.txt

# Keep only lines with our special separator
grep "___---___" rawlist.txt > rawlist.tmp
mv rawlist.tmp rawlist.txt


#
# The input filenames generated by our VLC snapshot (Ctrl + s). Path is different for Windows and Linux VLC client.
#
# ___---___00_13_44___---___file____home_jarleven_Pictures_syd__2019-05-25__20-45-01.mp4___---___Ein vill laks___---___2019-05-25-13h02m14s271.png
# ___---___00_13_44___---___file____home_jarleven_Pictures_nord__2019-05-25__20-45-01.mp4___---___Ein vill laks___---___2019-05-25-13h02m14s271.png
# ___---___00_00_22___---___file____run_user_1000_gvfs_sftp%3Ahost%3D192.168.1.151_media_jarleven_6d7e66e8-f56b-497c-91c4-dc3a4db5924f_laksen2019_syd__2019-05-25__15-45-01.mp4___---___2019-05-25-07h17m02s121.png
#

# TODO For more camera angles consider this as an array !

#Remove the path from the filename generated by VLC
sed -i -e "s/file____.*_syd__/syd__/g" rawlist.txt
sed -i -e "s/file____.*_nord__/nord__/g" rawlist.txt


#
# Each line should look something like this
#
# ___---___00_13_44___---____syd__2019-05-25__20-45-01.mp4___---___Ein vill laks___---___2019-05-25-13h02m14s271.png

#
 
# Get the columns with the timestamp and the filename
# The duration of the clip is by default 30 seconds
awk -F "___---___" '{print $2 " " $3 " 30" " " $4}' rawlist.txt > timestamps.txt

#
# Our standard format used to generate videoclips from our videoarchive
# This is saved as timestamps.txt
#
#  Offset -Filename                      -D -Metadata title
# 
# 00_13_44 _syd__2019-05-25__20-45-01.mp4 30 Ein vill laks
#




